# Imports

In [9]:

import sys

if "google.colab" in sys.modules:
  %pip install QuantLib
  %pip install optax
  %pip install qiskit
  %pip install qcware

  %pip install qcware-quasar
  ! rm -rf deep-hedging
  ! git clone https://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@github.com/SnehalRaj/jpmc-qcware-deephedging deep-hedging
  ! cp -r deep-hedging/* .

In [10]:

import config
import numpy as np
import jax
from tqdm import tqdm
import optax
from functools import partial 
import pickle 

from qnn import linear, ortho_linear, ortho_linear_noisy, ortho_linear_hardware
from train import build_train_fn
from models import simple_network, recurrent_network_hardware, lstm_network_hardware, attention_network
from loss_metrics import entropy_loss
from data import gen_paths
from utils import train_test_split, get_batches, HyperParams

In [11]:
np.set_printoptions(formatter={'float': "{0:0.3f}".format})

# Data

We begin by import the modules from the repository. Then to generate test data using geometric Brownian motion we use the `gen_paths()` function in `data.py`. 

Note: The data generation has been commented here because we pickled a particular test split. 

In [12]:
seed = 100
key = jax.random.PRNGKey(seed)
# No need to generate data as we load from disk
# hps = HyperParams(S0=100,
#                   n_steps=5,
#                   n_paths=10000,
#                   discrete_path=False,
#                   strike_price=100,
#                   epsilon=0.0,
#                   sigma=0.2,
#                   risk_free=0,
#                   dividend=0,
#                   model_type='simple',
#                   layer_type='noisy_ortho',
#                   n_features=8,
#                   n_layers=1,
#                   loss_param=1.0,
#                   batch_size=4,
#                   test_size=0.2,
#                   optimizer='adam',
#                   learning_rate=1E-3,
#                   num_epochs=100
#                   )


# Data
# S = gen_paths(hps)
# [S_train, S_test] = train_test_split([S], test_size=0.2)
# _, test_batches = get_batches(jnp.array(S_test[0]), batch_size=hps.batch_size)
# test_batch = test_batches[0]


# DeepHedgingBenchmark()

This is a class to benchmark the performance of different models and layers for deep hedging. It has one main method __test_model() which is used to perform inference using the layers and models specified in the input. Note that choosing `hps.layer_type` to `ortho_linear_hardware()` runs inference on hardware backend using `run_circuit()` function defined above. 

#### Parameters
- `key`: A random key value used for jax random splitting.
- `eps`: A list of float values representing the hedge intervals to be used in training.
- `layers`: A list of string values representing the layer types to be used in 
training. It should only contain values from `['linear', 'ortho', 'noisy_ortho', 'hardware_ortho']`.
- `models`: A list of string values representing the model types to be used in training. It should only contain values from `['simple', 'recurrent', 'lstm', 'attention']`.

#### Methods
- `__test_model(hps,test_batch,backend_name, device_id, params_dir)`: A private method that tests the model. It takes in hyperparameters hps, a batch of paths `test_batch` to run inference on and `params_dir` which specifies where to load the saved model parameters from. The hyperparameters include layer_type, model_type, n_steps, epsilon, and num_epochs. It returns the testing loss.
- `test(test_batch)`:  A method to test the model. It takes in `test_batch` which is the testing data and then output the necessary information about the model. It outputs the layer, the model architecture, the utility on these paths and the number of circuits executed. It also prints the output actions for each day and the Terminal PnL for each paths. 

In [13]:
from utils import load_params
from hardware_utils import prepare_circuit, run_circuit
class DeepHedgingBenchmark():
  """
  Runs the benchmark with different models / layers
  Input: test_batch above
  test_batch has 8 datapoints
  """
  def __init__(self, key, eps,  layers, models):
      self.__key = key
      self.__models = models
      self.__layers = layers
      self.__eps = eps
      self.test_info = {layer:{str(eps):{} for eps in self.__eps} for layer in self.__layers}
  def __test_model(self, hps, test_batch,backend_name, device_id, params_dir):
    global_number_of_circuits_executed = 0
    global_hardware_run_results_dict = {
        'model_type' : hps.model_type,
        'measurementRes' : None,
        'epsilon' : hps.epsilon,
        'backend_name' : None,
        'layer_type' : hps.layer_type,
        'batch_idx' : 0,
    }
    config.global_number_of_circuits_executed = global_number_of_circuits_executed  
    config.global_hardware_run_results_dict = global_hardware_run_results_dict
    if hps.layer_type in ['linear','linear_svb']:
      layer_func = linear
    elif hps.layer_type=='ortho':
      layer_func = ortho_linear
    elif hps.layer_type=='noisy_ortho':
      layer_func = partial(ortho_linear_noisy,noise_scale=0.01)
    elif hps.layer_type=='hardware_ortho':
      # TODO want to run this on Quantinuum device 
      layer_func = partial(ortho_linear_hardware,prepare_circuit, partial(run_circuit,device_id = device_id,backend_name = backend_name) )

    if hps.model_type == 'simple':
      net = simple_network(hps=hps, layer_func=layer_func)
    elif hps.model_type == 'recurrent':
      net = recurrent_network_hardware(hps=hps, layer_func=layer_func)
    elif hps.model_type == 'lstm':
      net = lstm_network_hardware(hps=hps, layer_func=layer_func)
    elif hps.model_type == 'attention':
      net = attention_network(hps=hps, layer_func=layer_func)
    
    opt = optax.adam(1E-3)
    key, init_key = jax.random.split(self.__key)
    _, state, _ = net.init(init_key, (1, hps.n_steps, 1))
    loss_metric = entropy_loss

    # Training

    train_fn, loss_fn = build_train_fn(hps, net, opt, loss_metric)

    train_info = load_params(params_dir)
    layer_type = "noisy_ortho" if hps.layer_type == 'hardware_ortho' else hps.layer_type
    train_losses, params = train_info[layer_type][str(hps.epsilon)][hps.model_type]
    loss, (state, wealths, deltas, outputs) = loss_fn(params, state, key, test_batch[...,None])
    print(f'Model = {hps.model_type} | Layer = {hps.layer_type} | EPS = {hps.epsilon}| Loss = {loss} | #circs = {global_number_of_circuits_executed}')
    # Display Deltas and Terminal PnL if batch size is small
    if len(test_batch < 10):
      print(f'Deltas = {deltas[...,0]}')
      print(f'Terminal PnL = {wealths.reshape(-1)}')
    return loss
  def test(self, inputs, backend_name, device_id, params_dir):
    for model in self.__models:
      for eps in self.__eps:
        for layer in self.__layers:
            hps = HyperParams(S0=100,
                  discrete_path=True,
                  strike_price=100,
                  epsilon=eps,
                  sigma=0.2,
                  risk_free=0,
                  dividend=0,
                  model_type=model,
                  layer_type=layer,
                  n_features=16,
                  n_layers=1,
                  loss_param=1.0,
                  batch_size=4,
                  test_size=0.2,
                  optimizer='adam',
                  learning_rate=1E-3,
                  num_epochs=100)
            self.test_info[layer][str(eps)][model] = self.__test_model(hps, inputs, backend_name, device_id, params_dir)
    



# Hardware Emulator Backend

## Load Test Data

In [14]:
# pickle.dump(test_batch, open('data/1103_test_batch_30_points.pickle', 'wb'))
test_batch = pickle.load(open('data/1103_test_batch_30_points.pickle', 'rb'))

### Simple, Recurrent, LSTM, and Attention

Non-emulator results:
30 days, 32 paths

```
Model = simple | Layer = linear | EPS = 0.01| Loss = 5.014517784118652 | #circs = 0
Model = simple | Layer = ortho | EPS = 0.01| Loss = 5.0412492752075195 | #circs = 0
Model = simple | Layer = noisy_ortho | EPS = 0.01| Loss = 5.003141403198242 | #circs = 0
Model = recurrent | Layer = linear | EPS = 0.01| Loss = 5.190323829650879 | #circs = 0
Model = recurrent | Layer = ortho | EPS = 0.01| Loss = 5.0067362785339355 | #circs = 0
Model = recurrent | Layer = noisy_ortho | EPS = 0.01| Loss = 4.838649272918701 | #circs = 0
Model = lstm | Layer = linear | EPS = 0.01| Loss = 4.761508941650391 | #circs = 0
Model = lstm | Layer = ortho | EPS = 0.01| Loss = 4.8098063468933105 | #circs = 0
Model = lstm | Layer = noisy_ortho | EPS = 0.01| Loss = 4.798060417175293 | #circs = 0
Model = attention | Layer = linear | EPS = 0.01| Loss = 4.776426315307617 | #circs = 0
Model = attention | Layer = ortho | EPS = 0.01| Loss = 4.846531391143799 | #circs = 0
Model = attention | Layer = noisy_ortho | EPS = 0.01| Loss = 4.843540191650391 | #circs = 0
```

In [15]:
LAYERS = ['hardware_ortho']
EPS = [  0.01]
MODELS = ['simple','recurrent','lstm','attention']

dhb = DeepHedgingBenchmark(key=key,eps=EPS, layers=LAYERS, models=MODELS)
dhb.test(test_batch, backend_name='quantinuum_H1-1E', device_id='1128_part_1', params_dir='params/params_all_models_16_qubits_30_days.pkl')

KeyboardInterrupt: 

# Hardware Backend 

## Load Test Data

In [ ]:
# pickle.dump(test_batch, open('data/1115_test_batch_4_points.pickle', 'wb'))
test_batch = pickle.load(open('data/1115_test_batch_4_points.pickle', 'rb'))

### LSTM model

Classical simulations results:
5 days, 4 paths

```
Model = lstm | Layer = linear | EPS = 0.01| Loss = 2.1739442348480225 | #circs = 0
Deltas = [[0.435 -0.002 -0.187 -0.182 -0.050 -0.014]
 [0.435 0.050 0.019 -0.001 -0.027 -0.476]
 [0.435 -0.015 -0.000 -0.085 -0.038 -0.296]
 [0.435 0.000 0.019 -0.001 -0.002 -0.451]]
Terminal PnL = [-2.578 -1.225 -1.420 -2.671]
Model = lstm | Layer = ortho | EPS = 0.01| Loss = 2.1762888431549072 | #circs = 0
Deltas = [[0.435 0.001 -0.203 -0.165 -0.049 -0.019]
 [0.435 0.051 0.011 -0.006 -0.045 -0.447]
 [0.435 -0.013 0.004 -0.090 -0.025 -0.310]
 [0.435 0.000 0.010 0.001 -0.001 -0.446]]
Terminal PnL = [-2.586 -1.194 -1.439 -2.671]
Model = lstm | Layer = noisy_ortho | EPS = 0.01| Loss = 2.1889312267303467 | #circs = 0
Deltas = [[0.437 0.004 -0.213 -0.158 -0.043 -0.027]
 [0.428 0.040 0.027 -0.009 -0.022 -0.463]
 [0.432 -0.019 0.000 -0.104 -0.018 -0.291]
 [0.435 -0.000 0.029 0.010 -0.001 -0.472]]
Terminal PnL = [-2.620 -1.205 -1.435 -2.669]
```

In [5]:
LAYERS = ['hardware_ortho']
EPS = [  0.01]
MODELS = ['lstm']

dhb = DeepHedgingBenchmark(key=key,eps=EPS, layers=LAYERS, models=MODELS)
dhb.test(test_batch, backend_name='quantinuum_H1-1', device_id='1115_device', params_dir='params/params_all_models_16_qubits_5_days.pkl')

### Attention Model

Non-emulator results:
5 days, 4 paths

```
Model = attention | Layer = linear | EPS = 0.01| Loss = 2.167210817337036 | #circs = 0
Deltas = [[0.429 0.001 -0.225 -0.121 -0.064 -0.020]
 [0.429 0.038 0.030 -0.001 -0.020 -0.475]
 [0.429 -0.007 -0.004 -0.092 -0.013 -0.312]
 [0.429 0.001 0.028 0.002 -0.000 -0.459]]
Terminal PnL = [-2.563 -1.219 -1.411 -2.673]
Model = attention | Layer = ortho | EPS = 0.01| Loss = 2.1953773498535156 | #circs = 0
Deltas = [[0.423 0.000 -0.167 -0.142 -0.095 -0.019]
 [0.423 0.062 0.023 -0.006 -0.056 -0.446]
 [0.423 -0.016 -0.014 -0.104 -0.040 -0.250]
 [0.423 0.005 0.031 0.003 -0.001 -0.462]]
Terminal PnL = [-2.639 -1.242 -1.388 -2.672]
Model = attention | Layer = noisy_ortho | EPS = 0.01| Loss = 2.4901790618896484 | #circs = 0
Deltas = [[0.435 -0.014 -0.083 -0.074 -0.051 -0.213]
 [0.413 0.095 0.015 -0.004 -0.130 -0.388]
 [0.426 -0.034 0.012 -0.111 -0.047 -0.246]
 [0.421 -0.010 0.029 0.012 0.004 -0.456]]
Terminal PnL = [-3.225 -1.270 -1.442 -2.728]
```

In [10]:
LAYERS = ['hardware_ortho']
EPS = [  0.01]
MODELS = ['attention']

dhb = DeepHedgingBenchmark(key=key,eps=EPS, layers=LAYERS, models=MODELS)
dhb.test(test_batch, backend_name='quantinuum_H1-1', device_id='1212_part1_2', params_dir='params/params_all_models_16_qubits_5_days.pkl')

Using precomputed counts from data/1212_part1_2_attention_quantinuum_H1-1_hardware_ortho_0.01_0.json


In [8]:
dhb.test(test_batch, backend_name='quantinuum_H1-1', device_id='1115_device', params_dir='params/params_all_models_16_qubits_5_days.pkl')

Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_0.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_1.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_2.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_3.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_4.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_5.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_6.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_7.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_8.json
Using precomputed counts from data/1115_device_lstm_quantinuum_H1-1_hardware_ortho_0.01_9.json
Using precomputed counts from data/1115_device_lst

In [9]:
# dhb.test(test_batch)